### ISSUE TITLE
Image content modified on upload.

### ISSUE THREAD

**Issue by tech-6** [lucko/bytebin#26]
When I have uploaded an `image/png` file to bytebin (both the public instance and my personal instance running commit de71d07) bytes are modified rendering the file invalid.

Original file (uploaded to backblaze): 
<a href='https://f002.backblazeb2.com/file/t-ch-screenshots/ShareX/2024/12/IMG_1593.png'><img src='https://f002.backblazeb2.com/file/t-ch-screenshots/ShareX/2024/12/IMG_1593.png' width=128></a>

Should match:
https://bytebin.lucko.me/NZF4EVsPOr
https://bytes.t-ch.net/NoE3eHf1SQYQntK

Curl log:
https://paste.t-ch.net/a3nuro0IxlTyGCS
https://paste.t-ch.net/EZ4H9Rdz8gSjTBg

Diff showing modification of images from src:
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/26c2f4e1-fa58-49d5-85d8-9094d6046554" />

P.S. Please excuse my friend's shocked face. He's as surprised as I am.

**Comment by lucko** [comment]
I suspect the issue is with your curl command. When using the `-d`/`--data` argument, curl will encode the request body using the `application/x-www-form-urlencoded` format unless overridden, and also do some conversions to newlines/carriage returns which I suspect is messing up the png data. Bytebin doesn't have any special handling to deal with`application/x-www-form-urlencoded`, and will just return the urlencoded form in subsequent GET requests.

I did however get it to work for me using `--data-binary`:

```
❯ curl -H "Content-Type: image/png" --data-binary @IMG_1593.png https://bytebin.lucko.me/post
{"key":"bG6mlAyW9a"}%
❯ curl -s -o- https://bytebin.lucko.me/bG6mlAyW9a | md5sum
222853b8d0e0e1d42398c6c5d23ba020  -
❯ md5sum IMG_1593.png
222853b8d0e0e1d42398c6c5d23ba020  IMG_1593.png
```

Or using the `-T`/`--upload-file` argument, which sends a PUT request instead:

```
❯ curl -T IMG_1593.png -H "Content-Type: image/png" https://bytebin.lucko.me/post
https://bytebin.lucko.me/xiATREVed
❯ curl -s -o- https://bytebin.lucko.me/xiATREVed | md5sum
222853b8d0e0e1d42398c6c5d23ba020  -
```

**Comment by tech-6** [comment]
Thats on me, thanks for the response!
